### ISSUE TITLE
i dont have a insider updates

### ISSUE THREAD

**Issue by oleggamer351** [abbodi1406/offlineinsiderenroll#20]
i checked all reinstalled this and restarted pc 
windows update downloads only default updates
screenshots is google translated because my windows using russian language
![9bed41d2-a0c9-4798-80c6-79472c8d7005](https://github.com/abbodi1406/offlineinsiderenroll/assets/131574761/b20c4571-603e-4759-a55a-6040e9f28422)
![ApplicationFrameHost_fzAgH3sWQF](https://github.com/abbodi1406/offlineinsiderenroll/assets/131574761/8001750f-8f34-409f-bee4-1f4912647885)
Edited:
im enabled diagnostics and feedback to full

**Comment by stdin82** [comment]
If your machine is not compatible with Windows 11, offlineinsiderenroll can't help

**Comment by oleggamer351** [comment]
my pc is compactible with windows 11
![6d618d9a-d4a5-43d2-94b1-d3281e5417fb](https://github.com/abbodi1406/offlineinsiderenroll/assets/131574761/09ec6fee-b5a8-4bdb-bdd8-9cf7153d9583)

**Comment by fishmohuman** [comment]
Hello, i don't think cmd is broken. I just ran the cmd and works fine for me. 
![image](https://github.com/abbodi1406/offlineinsiderenroll/assets/107815169/a4d7abc0-3a65-4fbe-8f6e-566d6525c0c8)

**Comment by Ramazik** [comment]
Use VPN in Russia

**Comment by oleggamer351** [comment]
@Ramazik i need vpn to use windows update with insider? Microsoft blocked all from windows in Russia

**Comment by oleggamer351** [comment]
Ok i try if problem not solves im say there and sorry for bad english

**Comment by Branca666** [comment]
how can fix this ? 

![image](https://github.com/user-attachments/assets/797a5674-47de-45d1-80d4-b4916be8165e)
